const express=require("express")
const usercontrol=require("./usercontrol")
const staffcontrol=require("./staffcontrol")
const foodcontrol=require('./foodcontrol')
const cartcontrol = require("./cartcontrol")
const router=express.Router()
router.post('/userregistration',usercontrol.userregistration)
router.post('/resetpassword',usercontrol.resetpassword)
router.post('/userlogin',usercontrol.userlogin)
router.post('/staffregistration',staffcontrol.staffregistration)
router.post('/stafflogin',staffcontrol.stafflogin)
router.post('/staffresetpassword',staffcontrol.staffresetpassword)
router.post('/addfood',foodcontrol.upload,foodcontrol.addfood)
router.get('/viewfood',foodcontrol.viewfood)
router.post('/deletefood',foodcontrol.deletefood)
router.post('/addcart/:foodid',cartcontrol.addcart)
router.get('/viewcart',cartcontrol.viewcart)

module.exports=router