const express=require("express")
const usercontrol=require("./usercontrol")
const staffcontrol=require("./staffcontrol")
const foodcontrol=require('./foodcontrol')
const cartcontrol = require("./cartcontrol")
const ordercontrol = require("./ordercontrol")
const staffcartcontrol = require("./staffcartcontrol")
const staffordercontrol = require("./staffordercontrol")
const router=express.Router()
router.post('/userregistration',usercontrol.userregistration)
router.post('/resetpassword',usercontrol.resetpassword)
router.post('/userlogin',usercontrol.userlogin)
router.post('/staffregistration',staffcontrol.staffregistration)
router.post('/stafflogin',staffcontrol.stafflogin)
router.post('/staffresetpassword',staffcontrol.staffresetpassword)
router.post('/addfood',foodcontrol.upload,foodcontrol.addfood)
router.get('/viewfood',foodcontrol.viewfood)
router.get('/viewone/:id',foodcontrol.viewone)
router.post('/editfooddetails/:id',foodcontrol.editfood)
router.post('/deletefood/:id',foodcontrol.deletefood)
router.post('/addcart/:foodid',cartcontrol.addcart)
router.get('/viewcart/:userid',cartcontrol.viewcart)
router.post('/deletecartitem/:id',cartcontrol.deletecartitem)
router.post('/cartitems/:userid',cartcontrol.deletecart)
router.post('/addorder',ordercontrol.addorder)
router.get('/vieworder/:userid',ordercontrol.vieworder)
router.post('/cancelorder',ordercontrol.cancelorder)
router.post('/paymentstatus',ordercontrol.paymentstatus)
router.get('/vieworderdetails/:userid',ordercontrol.vieworderdetails)
router.post('/staffaddcart/:foodid',staffcartcontrol.staffaddcart)
router.get('/staffviewcart/:staffid',staffcartcontrol.staffviewcart)
router.get('/viewcustomerorder',ordercontrol.viewcustomerorder)
router.post('/staffdeletecartitem/:id',staffcartcontrol.staffdeletecartitem)
router.post('/staffaddorder/:customername',staffordercontrol.staffaddorder)
router.get('/stafforderdetails/:staffid',staffordercontrol.stafforderdetails)
router.get('/viewstafforders',staffordercontrol.viewallstafforder)

module.exports=router